### ISSUE TITLE
release: v0.15.0-rc1 required reviews

### ISSUE THREAD

**Issue by materializer** [MaterializeInc/uid-buildkite-plugin#7]
The following PRs in [`v0.15.0-rc1`](https://github.com/MaterializeInc/materialize/tree/v0.15.0-rc1) require review:
* [ ] [#9761 doc/developer/guide: update Homebrew installation instructions](https://github.com/MaterializeInc/materialize/pull/9761) (@benesch)
* [ ] [#9769 scratch: fix provisioning](https://github.com/MaterializeInc/materialize/pull/9769) (@benesch)
* [ ] [#9771 ci: ensure the deploy job waits for all tests to complete](https://github.com/MaterializeInc/materialize/pull/9771) (@benesch)
* [ ] [#9776 ci/test: handle wait steps when trimming pipelines](https://github.com/MaterializeInc/materialize/pull/9776) (@benesch)
* [ ] [#9775 demo/chbench: remove old benchmarking cruft](https://github.com/MaterializeInc/materialize/pull/9775) (@benesch)
* [ ] [#9797 mzbuild: use --dev flag rather than --mz-build-mode=dev](https://github.com/MaterializeInc/materialize/pull/9797) (@benesch)
* [ ] [#9798 mzcompose: introduce a list command](https://github.com/MaterializeInc/materialize/pull/9798) (@benesch)
* [ ] [#9803 Continue 0.14.1 dev](https://github.com/MaterializeInc/materialize/pull/9803) (@benesch)
* [ ] [#9804 cloudbench: fix](https://github.com/MaterializeInc/materialize/pull/9804) (@benesch)
* [ ] [#9808 mzcompose: handle run arguments properly](https://github.com/MaterializeInc/materialize/pull/9808) (@benesch)
* [ ] [#9822 nightly: remove stray upgrade job](https://github.com/MaterializeInc/materialize/pull/9822) (@benesch)
* [ ] [#9829 test/performance: remove directory](https://github.com/MaterializeInc/materialize/pull/9829) (@benesch)
* [ ] [#9828 test/perf-upsert: remove](https://github.com/MaterializeInc/materialize/pull/9828) (@benesch)
* [ ] [#9840 doc/developer: Fix broken link in testing guide](https://github.com/MaterializeInc/materialize/pull/9840) (@jkosh44)
* [ ] [#9834 mzcompose: remove self test](https://github.com/MaterializeInc/materialize/pull/9834) (@benesch)
* [ ] [#9833 perf-kinesis: port to mzworkflows.py](https://github.com/MaterializeInc/materialize/pull/9833) (@benesch)
* [ ] [#9835 mzcompose: add Workflow.run_sql convenience method](https://github.com/MaterializeInc/materialize/pull/9835) (@benesch)
* [ ] [#9838 ci/test: remove IDs from jobs](https://github.com/MaterializeInc/materialize/pull/9838) (@benesch)
* [ ] [#9851 Python dependency bump 2022-01-02](https://github.com/MaterializeInc/materialize/pull/9851) (@benesch)

The following commits in this release were not associated with any PR and therefore require review:
* [ ] [`078be6ebc` ci/test: fix short-circuiting when trimming pipeline](https://github.com/MaterializeInc/materialize/commit/078be6ebc91b78054bb43b8a1f10447dd567ad90) (@benesch)
* [ ] [`00e3c76c8` release: v0.15.0-rc1](https://github.com/MaterializeInc/materialize/commit/00e3c76c8664ef0565f07a8e65dac8428e3e4e71) (@petrosagg)

**Comment by materializer** [comment]
All PRs and unassociated commits:

* [ ] [#9643 add kafka config property](https://github.com/MaterializeInc/materialize/pull/9643) (@nharring-adjacent)
* [ ] [#9761 doc/developer/guide: update Homebrew installation instructions](https://github.com/MaterializeInc/materialize/pull/9761) (@benesch)
* [ ] [#9762 *: deoptionalize column names everywhere](https://github.com/MaterializeInc/materialize/pull/9762) (@benesch)
* [ ] [#9760 ci: add instructions for spinning up CI-like infrastructure](https://github.com/MaterializeInc/materialize/pull/9760) (@benesch)
* [ ] [#9763 scratch: handle host repository being in detached HEAD mode](https://github.com/MaterializeInc/materialize/pull/9763) (@benesch)
* [ ] [#9764 scratch: use pydantic to decode JSON from stdin](https://github.com/MaterializeInc/materialize/pull/9764) (@benesch)
* [ ] [#9751 coord: allow timestamp-independent txns to get a timedomain](https://github.com/MaterializeInc/materialize/pull/9751) (@mjibson)
* [ ] [#9768 sql: restrict window function planning to SELECT and ORDER BY](https://github.com/MaterializeInc/materialize/pull/9768) (@mjibson)
* [ ] [#9769 scratch: fix provisioning](https://github.com/MaterializeInc/materialize/pull/9769) (@benesch)
* [ ] [#9771 ci: ensure the deploy job waits for all tests to complete](https://github.com/MaterializeInc/materialize/pull/9771) (@benesch)
* [ ] [#9772 pyactivate: pass --use-pep517 to suppress wheel warning](https://github.com/MaterializeInc/materialize/pull/9772) (@benesch)
* [ ] [#9776 ci/test: handle wait steps when trimming pipelines](https://github.com/MaterializeInc/materialize/pull/9776) (@benesch)
* [ ] [#9775 demo/chbench: remove old benchmarking cruft](https://github.com/MaterializeInc/materialize/pull/9775) (@benesch)
* [ ] [#9781 Allow TD_TEST to be used to control the persistence test](https://github.com/MaterializeInc/materialize/pull/9781) (@philip-stoev)
* [ ] [#9783 expr: make predicate canonizalization output reliable](https://github.com/MaterializeInc/materialize/pull/9783) (@asenac)
* [ ] [#9785 coord: loosen invariants in test_tail_table_rw_timestamps](https://github.com/MaterializeInc/materialize/pull/9785) (@sploiselle)
* [ ] [#9780 scratch: restore default instance profile](https://github.com/MaterializeInc/materialize/pull/9780) (@benesch)
* [ ] [#9786 sql: allow planning of DISTINCT ON with window functions](https://github.com/MaterializeInc/materialize/pull/9786) (@mjibson)
* [ ] [#9788 extend startup timeout for persistence tests](https://github.com/MaterializeInc/materialize/pull/9788) (@guswynn)
* [ ] [#9787 add one off creation and --ssh to bin/scratch create](https://github.com/MaterializeInc/materialize/pull/9787) (@guswynn)
* [ ] [#9791 persist: refactor Listen{Event,Fn} to always use Vec<u8>s](https://github.com/MaterializeInc/materialize/pull/9791) (@ruchirK)
* [ ] [#9789 Ensure multi-instance testdrive tests are repeatable](https://github.com/MaterializeInc/materialize/pull/9789) (@guswynn)
* [ ] [#9790 mzcompose: rewrite command-line driver](https://github.com/MaterializeInc/materialize/pull/9790) (@benesch)
* [ ] [#9726 sql: Let support in Hir](https://github.com/MaterializeInc/materialize/pull/9726) (@asenac)
* [ ] [#9797 mzbuild: use --dev flag rather than --mz-build-mode=dev](https://github.com/MaterializeInc/materialize/pull/9797) (@benesch)
* [ ] [#9798 mzcompose: introduce a list command](https://github.com/MaterializeInc/materialize/pull/9798) (@benesch)
* [ ] [#9799 ci-builder: fall back to shasum on macOS](https://github.com/MaterializeInc/materialize/pull/9799) (@benesch)
* [ ] [#9774 optbench: use pg8000 instead of psycopg2](https://github.com/MaterializeInc/materialize/pull/9774) (@benesch)
* [ ] [#9778 doc/user: polish release notes for v0.14.0](https://github.com/MaterializeInc/materialize/pull/9778) (@benesch)
* [ ] [#9803 Continue 0.14.1 dev](https://github.com/MaterializeInc/materialize/pull/9803) (@benesch)
* [ ] [#9804 cloudbench: fix](https://github.com/MaterializeInc/materialize/pull/9804) (@benesch)
* [ ] [#9807 misc/tb: remove](https://github.com/MaterializeInc/materialize/pull/9807) (@benesch)
* [ ] [#9808 mzcompose: handle run arguments properly](https://github.com/MaterializeInc/materialize/pull/9808) (@benesch)
* [ ] [#9810 dbt-materialize: convert mzcompose.yml to mzworkflows.py](https://github.com/MaterializeInc/materialize/pull/9810) (@benesch)
* [ ] [#9811 mzcompose,test/upgrade: overhaul workflow interface](https://github.com/MaterializeInc/materialize/pull/9811) (@benesch)
* [ ] [#9800 persist: have listen take a Sender for events instead of a callback](https://github.com/MaterializeInc/materialize/pull/9800) (@ruchirK)
* [ ] [#9818 play/mbta: convert to mzworkflows.py](https://github.com/MaterializeInc/materialize/pull/9818) (@benesch)
* [ ] [#9822 nightly: remove stray upgrade job](https://github.com/MaterializeInc/materialize/pull/9822) (@benesch)
* [ ] [#9823 test/pg-cdc: convert to mzworkflows.py](https://github.com/MaterializeInc/materialize/pull/9823) (@benesch)
* [ ] [#9795 expr: make predicate canonizalization output reliable (attempt 2)](https://github.com/MaterializeInc/materialize/pull/9795) (@asenac)
* [ ] [#9824 wikirecent: simplify, copyedit, and port to mzworkflows.py](https://github.com/MaterializeInc/materialize/pull/9824) (@benesch)
* [ ] [#9820 test/kafka-exactly-once: convert to mzworkflows.py](https://github.com/MaterializeInc/materialize/pull/9820) (@benesch)
* [ ] [#9829 test/performance: remove directory](https://github.com/MaterializeInc/materialize/pull/9829) (@benesch)
* [ ] [#9832 test/chaos: remove](https://github.com/MaterializeInc/materialize/pull/9832) (@benesch)
* [ ] [#9828 test/perf-upsert: remove](https://github.com/MaterializeInc/materialize/pull/9828) (@benesch)
* [ ] [#9840 doc/developer: Fix broken link in testing guide](https://github.com/MaterializeInc/materialize/pull/9840) (@jkosh44)
* [ ] [#9834 mzcompose: remove self test](https://github.com/MaterializeInc/materialize/pull/9834) (@benesch)
* [ ] [#9833 perf-kinesis: port to mzworkflows.py](https://github.com/MaterializeInc/materialize/pull/9833) (@benesch)
* [ ] [#9835 mzcompose: add Workflow.run_sql convenience method](https://github.com/MaterializeInc/materialize/pull/9835) (@benesch)
* [ ] [#9827 test/kafka-multi-broker: port to mzworkflows.py](https://github.com/MaterializeInc/materialize/pull/9827) (@benesch)
* [ ] [#9838 ci/test: remove IDs from jobs](https://github.com/MaterializeInc/materialize/pull/9838) (@benesch)
* [ ] [#9841 kgen: parallelize](https://github.com/MaterializeInc/materialize/pull/9841) (@benesch)
* [ ] [#9851 Python dependency bump 2022-01-02](https://github.com/MaterializeInc/materialize/pull/9851) (@benesch)
* [ ] [#9852 python: fix exit code on failure](https://github.com/MaterializeInc/materialize/pull/9852) (@benesch)
* [ ] [#9541 build(deps): bump sha2 from 0.9.8 to 0.10.0](https://github.com/MaterializeInc/materialize/pull/9541) (@dependabot[bot])
* [ ] [#9854 build(deps): bump pin-project from 1.0.9 to 1.0.10](https://github.com/MaterializeInc/materialize/pull/9854) (@dependabot[bot])
* [ ] [#9860 build(deps): bump serde_json from 1.0.73 to 1.0.74](https://github.com/MaterializeInc/materialize/pull/9860) (@dependabot[bot])
* [ ] [#9859 build(deps): bump rdkafka from `bbd3417` to `7a2355f`](https://github.com/MaterializeInc/materialize/pull/9859) (@dependabot[bot])
* [ ] [#9864 build(deps): bump num_enum from 0.5.5 to 0.5.6](https://github.com/MaterializeInc/materialize/pull/9864) (@dependabot[bot])
* [ ] [#9858 build(deps): bump pubnub-hyper from `3e3b90e` to `9da4f3e`](https://github.com/MaterializeInc/materialize/pull/9858) (@dependabot[bot])
* [ ] [#9856 build(deps): bump tracing-subscriber from 0.3.4 to 0.3.5](https://github.com/MaterializeInc/materialize/pull/9856) (@dependabot[bot])
* [ ] [#9857 build(deps): bump sysinfo from 0.22.3 to 0.22.4](https://github.com/MaterializeInc/materialize/pull/9857) (@dependabot[bot])
* [ ] [#9855 build(deps): bump proc-macro2 from 1.0.35 to 1.0.36](https://github.com/MaterializeInc/materialize/pull/9855) (@dependabot[bot])
* [ ] [#9869 build(deps): bump quote from 1.0.10 to 1.0.14](https://github.com/MaterializeInc/materialize/pull/9869) (@dependabot[bot])
* [ ] [#9867 build(deps): bump serde from 1.0.132 to 1.0.133](https://github.com/MaterializeInc/materialize/pull/9867) (@dependabot[bot])
* [ ] [#9868 build(deps): bump http from 0.2.5 to 0.2.6](https://github.com/MaterializeInc/materialize/pull/9868) (@dependabot[bot])
* [ ] [#9830 doc/user: pin demos to latest stable release](https://github.com/MaterializeInc/materialize/pull/9830) (@benesch)
* [ ] [#9865 deps: upgrade to clap v3](https://github.com/MaterializeInc/materialize/pull/9865) (@benesch)

* [ ] [`078be6ebc` ci/test: fix short-circuiting when trimming pipeline](https://github.com/MaterializeInc/materialize/commit/078be6ebc91b78054bb43b8a1f10447dd567ad90) (@benesch)
* [ ] [`00e3c76c8` release: v0.15.0-rc1](https://github.com/MaterializeInc/materialize/commit/00e3c76c8664ef0565f07a8e65dac8428e3e4e71) (@petrosagg)

**Comment by petrosagg** [comment]
All looks good
